### ISSUE TITLE
Should you send the commands out more often?

### ISSUE THREAD

**Issue by sbender9** [joabakk/signalk-instrument-light-plugin#6]
Very cool! Will figure out how Raymarine does it over N2K and add that...

Here's what super annoying for me related to this:

* Instruments lights turned way down when dropping the hook at night
* Turn most instruments off to conserve battery
* In the morning, ready to leave. Turn things back on, can't see sh*t

Would be really cool if those quickly had the brightness turned back up automatically.

So maybe send out the light setting every 30 seconds or so? That way any instruments that were not on at the last check will get updated.

**Comment by joabakk** [comment]
Good idea. Currently I only have control of the lights on my tiller pilot, but I'm hoping for more control. The more types of instruments, the longer it takes to figure out and adjust each one

**Comment by joabakk** [comment]
https://github.com/joabakk/signalk-instrument-light-plugin/commit/27fc59cdd706e98eace2c01a8ab7b48e02ed0149 should enable this 30s repeat
